#!/usr/bin/env python3
"""
Daily Briefing Scheduler - Generates morning summary every day.

Creates daily briefing document with:
- Pending tasks count
- Yesterday's completions
- Today's priorities
- Urgent items

Usage:
    python scripts/daily_scheduler.py ./AI_Employee_Vault
"""

import os
import sys
from pathlib import Path
from datetime import datetime, timedelta
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

def count_files(folder: Path, extension: str = '.md') -> int:
    """Count files with extension in folder."""
    if not folder.exists():
        return 0
    return len([f for f in folder.iterdir() if f.suffix == extension])

def count_done_yesterday(done_folder: Path) -> int:
    """Count files moved to Done yesterday."""
    if not done_folder.exists():
        return 0
    
    yesterday = datetime.now() - timedelta(days=1)
    yesterday_str = yesterday.strftime('%Y-%m-%d')
    
    count = 0
    for f in done_folder.glob('*.md'):
        try:
            mtime = datetime.fromtimestamp(f.stat().st_mtime)
            if mtime.strftime('%Y-%m-%d') == yesterday_str:
                count += 1
        except:
            pass
    
    return count

def get_pending_items(needs_action: Path) -> list:
    """Get list of pending items."""
    if not needs_action.exists():
        return []
    return [f.name for f in needs_action.glob('*.md')]

def get_urgent_approvals(pending_approval: Path) -> list:
    """Get items requiring urgent approval."""
    if not pending_approval.exists():
        return []
    
    urgent = []
    for f in pending_approval.glob('*.md'):
        content = f.read_text(encoding='utf-8')
        if 'priority: high' in content or 'urgent' in content.lower():
            urgent.append(f.name)
    
    return urgent

def generate_daily_briefing(vault_path: str):
    """Generate daily briefing document."""
    vault = Path(vault_path)
    briefings = vault / 'Briefings'
    briefings.mkdir(exist_ok=True)
    
    # Get counts
    needs_action = vault / 'Needs_Action'
    done = vault / 'Done'
    pending_approval = vault / 'Pending_Approval'
    
    pending_count = count_files(needs_action)
    done_yesterday = count_done_yesterday(done)
    pending_items = get_pending_items(needs_action)
    urgent_approvals = get_urgent_approvals(pending_approval)
    
    # Create briefing
    today = datetime.now().strftime('%Y-%m-%d')
    content = f"""---
created: {datetime.now().isoformat()}
type: daily_briefing
date: {today}
---

# Daily Briefing: {datetime.now().strftime('%B %d, %Y')}

## Quick Summary

| Metric | Value |
|--------|-------|
| Pending Tasks | {pending_count} |
| Completed Yesterday | {done_yesterday} |
| Urgent Approvals | {len(urgent_approvals)} |

"""
    
    # Pending items
    content += "## Pending Items\n\n"
    if pending_items:
        for item in pending_items[:10]:  # Show max 10
            content += f"- [ ] {item}\n"
    else:
        content += "- [ ] No pending items\n"
    
    content += "\n"
    
    # Urgent approvals
    content += "## Urgent Approvals\n\n"
    if urgent_approvals:
        for item in urgent_approvals:
            content += f"- ⚠️ {item}\n"
    else:
        content += "- ✅ No urgent approvals\n"
    
    content += f"""

## Today's Priorities

1. Process pending items in Needs_Action/
2. Review and approve pending approvals
3. Check Dashboard.md for updates

## Notes

```
Add today's notes here
```

---
*Generated by AI Employee Daily Scheduler*
"""
    
    # Write file
    output = briefings / f'{today}_daily_briefing.md'
    output.write_text(content)
    
    print(f"✓ Daily briefing created: {output}")
    return output


def main():
    """Main entry point."""
    # Use environment variable or command line argument
    vault_path = os.getenv('VAULT_PATH', './AI_Employee_Vault')
    
    if len(sys.argv) > 1:
        vault_path = sys.argv[1]
    
    generate_daily_briefing(vault_path)


if __name__ == '__main__':
    main()
